AIKE_APP/Controllers/ProjectController.cs
using AIKE_APP.Filter;
using AIKE_Model;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AIKE_APP.Controllers
{
    public class ProjectController : Controller
    {
        // GET: Project
        public ActionResult Index()
        {

            return View();
        }
        [PersonCheckFilterAttribute(IsCheck = true)]
        public ActionResult ProjectDetail(string path)
        {
            Session["LoginName"] = "Project/ProjectDetail";
            ViewData["photo"] = "";
            return View();
        }
        [PersonCheckFilterAttribute(IsCheck = true)]
        public ActionResult Returns()
        {
            int money =Convert.ToInt32( Request.QueryString["money"]);
            ViewData["Paymoney"] = money;
            return View();
        }
        /// <summary>
        /// 图像识别
        /// </summary>
        /// <param name="path"></param>
        /// <returns></returns>
        public string Pro(string path)
        {
            List<string> list = new List<string>();
            list = AIKE_BLL.BaiDuAI.ImageRecognition(path);
            return JsonConvert.SerializeObject(list);
        }

        /// <summary>
        /// 文本纠查
        /// </summary>
        /// <param name="oldstr"></param>
        /// <returns></returns>
        public string NewTxet(string oldstr)
        {
            string newstr = AIKE_BLL.BaiDuAI.TextCorrection(oldstr);
            return newstr;
        }
        public string Detection(string strs)
        {
            int i = AIKE_BLL.BaiDuAI.TextDetection(strs);
            return i.ToString();
        }


        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            var path = $"/Images/{file.FileName}";
            file.SaveAs(Server.MapPath(path));      //保存文件
            string fname = file.FileName;
            Session["sphoto"] = fname;
            return Redirect("../Project/ProjectDetail");
        }
        public string getPhoto()
        {
            return Session["sphoto"].ToString();
        }
        public ActionResult File()
        {
            return View();
        }

        [PersonCheckFilterAttribute(IsCheck = true)]
        public ActionResult ProjectReturn()
        {
            return View();
        }

        /// <summary>
        /// 添加项目
        /// </summary>
        /// <param name="name">项目名称</param>
        /// <param name="days">筹集天数</param>
        /// <param name="money">筹集金额</param>
        /// <param name="Add">发起地址</param>
        /// <param name="Details">项目详情</param>
        /// <param name="Introduction">项目简介</param>
        public void AddProject(string name, int days, decimal money, string Add, string Details, string Introduction, string Label)
        {
            Project project = new Project()
            {
                ProjectAddress = Add,
                ProjectCover = "",
                ProjectDetail = Details,
                ProjectIntroduction = Introduction,
                ProjectName = name,
                ProjectTypeID = 1,
                RaiseDays = days,
                RaiseMoney = money,
                State = 0,
                Label = Label,
                ReleaseTime = DateTime.Parse("2010-2-12")

            };
            AIKE_BLL.DataManager.project = project;
        }

        public void AddReturn(int Money, int number, string Content, int time)
        {
            ProjectReturn projectReturn = new ProjectReturn()
            {
                SupportMoney = Money,
                Number = number,
                ReturnContent = Content,
                ReturnTime = time
            };
            AIKE_BLL.DataManager.list.Add(projectReturn);
        }
        public void AddNumber()
        {
            AIKE_BLL.DataManager.addProject();
        }

    }
}

AIKE_APP/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AIKE_Model;
using AIKE_APP.Models;
using Newtonsoft.Json;
using AIKE_BLL;
namespace AIKE_APP.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            List<Userinfo> list = AIKE_BLL.DataManager.chackListmanager();

            ViewData["list"] = list;

            return View();
        }
        public ActionResult tt()
        {
       // 客户端ip:
           string id= Request.ServerVariables.Get("Remote_Addr").ToString();
       // 客户端主机名:
           string name= Request.ServerVariables.Get("Remote_Host").ToString();
           // 客户端浏览器IE：
      

       /// 服务器ip:
          string sid=  Request.ServerVariables.Get("Local_Addr").ToString();
            ///服务器名：  
           string sname= Request.ServerVariables.Get("Server_Name").ToString();

            return View();
        }

        public string delete(string id)
        {
            int toId = Convert.ToInt32(id);

            bool b = AIKE_BLL.DataManager.deletemanager(toId);

            if (b)
            {
                return "1";
            }
            else
            {
                return "0";
            }
            
        }

        //public string test(string name)
        //{
        //    //Msg s = new Msg();
        //    //s.discript = "成功！";
        //    //s.status = 1;
        //    //return JsonConvert.SerializeObject(s);
        //}
    }
}

AIKE_APP/Views/Test/Index.cshtml
@{
    Layout = null;
}
@using AIKE_Model;

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Common/jquery-3.1.1.js"></script>
    <script>
        $(function () {

            $("#btn").click(function () {
                $.ajax({

                    url: "../Test/test",//提交地址：控制器/方法
                    data: { "name": $("#name").val() },
                    success: function (data) {
                        debugger
                        alert(data[0])
                    },
                    error: function () {

                    }
                });


            });;

        });
    </script>
</head>
<body>
    <div> 
        <table>
            @foreach (Userinfo u in (List<Userinfo>)ViewData["list"])
            { 
            <tr> <td>@u.UserID</td>  <td>@u.NickName</td> <td>@u.AccountNumber</td>  <td>@u.Gender</td></tr>
            }
        </table>
        <input type="text" id="name" />
        <button id="btn">提交</button>
    </div>
</body>
</html>

AIKE_APP/Views/Test/tt.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>tt</title>
    <script src="~/Common/jquery-3.1.1.js"></script>
</head>
<body>
    <script src="~/Common/ajaxfileupload.js"></script>
    <div>
        <input type="file" id="file" />
    </div>
    <script>
    $(function () {
        $("#file").change(function () {
            alert()
            $.ajaxFileUpload({
                    url: '@Url.Action("FileUpload", "Project")',
                    datatype: "json",
                    type:"post",
                    secureuri: false,
                    fileElementId: 'file',//文件input标签id
                    data: {},
                success: function (data) {
                    debugger
                   
                },
                error: function (data) {
                    debugger
                   
                }
            });

        });
    });
    </script>


</body>
</html>